#!/bin/bash

if [[ ! -x ./sudoku ]]
then
	go build sudoku
fi

rm -rf output
mkdir output

INNUMBERS=$(ls -1 tests/[0-9][0-9])

if [[ ! -z $1 ]]
then
	INNUMBERS=tests/$1
fi

for IN in $INNUMBERS
do
	B=$(basename $IN)
	OUT=output/$B

	echo $B

	if ./sudoku -f < $IN > $OUT
	then
		if diff desired/$B $OUT > /dev/null
		then
			:
		else
			echo "Problem with test $B"
			echo "diff {output,desired}/$B"
			echo "./cmp {output,desired}/$B"
		fi
	else
		echo "Problem with sudoku on $IN: $?"
	fi
done
